### ISSUE TITLE
Labels with only numbers as value breaks deployment/sts templates

### ISSUE THREAD

**Issue by jess-sol** [cdapio/cdap-operator#27]
I have a label automatically added to the cdap resource with a number as its value, it looks like:

```
kapp.k14s.io/app=1583512484380481917
```

This breaks the `cdap-deployment.yaml` and `cdap-sts.yaml` templates, because label values aren't quoted, and may be interpreted as a number (instead of a string). I'd image the same would happen for truthy/falsy values.

Here's an example error message from the operator:

```
E0310 17:46:06.200716       1 genericreconciler.go:51] Failed: [*v1alpha1.CDAPMaster/default/cdap] gathering expected resources. templates/cdap-sts.yaml:v1.StatefulSet.ObjectMeta: v1.ObjectMeta.Labels: ReadStr
ing: expects " or n, but found 1, error found in #10 byte of ...|.io/app":15835124843|..., bigger context ...|urce-namespace":"default","kapp.k14s.io/app":1583512484380481917,"kapp.k14s.io/association":"v1.|..
.
2020/03/10 17:46:06 *v1alpha1.CDAPMaster/default/cdap(cmpnt:*cdapmaster.Messaging)  } reconciling component
E0310 17:46:06.200746       1 genericreconciler.go:114] error reconciling *v1alpha1.CDAPMaster/default/cdap. templates/cdap-sts.yaml:v1.StatefulSet.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n,
 but found 1, error found in #10 byte of ...|.io/app":15835124843|..., bigger context ...|urce-namespace":"default","kapp.k14s.io/app":1583512484380481917,"kapp.k14s.io/association":"v1.|...
```

I think most (all?) values in these templates should be quoted, to avoid these types of issues. At least the label values should be.

Happy to put in a PR for this, but wanted feedback first. I'd like to go through and quote everything that has foreign data in it.

**Comment by chtyim** [comment]
I agree. Please feel free to open a PR for the fix.

**Comment by jess-sol** [comment]
PR merged, thanks!
