### ISSUE TITLE
Further steps to install CDAP components

### ISSUE THREAD

**Issue by nitinaintahero** [cdapio/cdap-operator#5]
Dear Group,

I could install CDAP-Operator. Please suggest what are the next steps to install cdap components like master-service, kafka, auth, router etc.

##
adminisatorsMBP:resources nitin.nanda$ kubectl get all -n system
NAME                    READY   STATUS    RESTARTS   AGE
pod/cdap-controller-0   1/1     Running   0          19h

NAME                              TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
service/cdap-controller-service   LoadBalancer   10.98.127.246   <pending>     443:31367/TCP   23h

NAME                               READY   AGE
statefulset.apps/cdap-controller   1/1     19h
adminisatorsMBP:resources nitin.nanda$ 

##

**Comment by nitinaintahero** [comment]
Fixed.

**Comment by daxtergithub** [comment]
> Fixed.

how do you fixed that do you have step to deploy cdap on kubernates , operator is fine it works
